# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish to Github_Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read # for accessing the repository contents
  id-token: write # for verifying the deployment source
  pages: write # to be able deploy to GitHub Pages

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.6.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js  ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: '11.6.0'
    - name: Install Dependencies.
      run: npm install
    - run: npm run build
    #- run: npm test
    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://https://github.com/CoderTea-1/Xenophobia.git
        npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#git remote add origin https://CoderTea-1/Xenophobia.git
